### ISSUE TITLE
Desc field of a state being implemented as optional while mandatory in the spec

### ISSUE THREAD

**Issue by CiottiGiorgio** [algorandfoundation/algokit-client-generator-ts#54]
In addition, it should be `desc` and not `descr`
https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0032.md#schema-specification

https://github.com/algorandfoundation/algokit-client-generator-ts/blob/2de43edd1540584897edd689a7ce143fe4bcdb25/src/schema/application.d.ts#L165
https://github.com/algorandfoundation/algokit-client-generator-ts/blob/2de43edd1540584897edd689a7ce143fe4bcdb25/src/schema/application.d.ts#L179

**Comment by neilcampbell** [comment]
@CiottiGiorgio Just checking in on this one.
The ARC was updated a few months ago and matches the code correctly now.
I believe I can close this issue now, however just wanted to confirm.

**Comment by CiottiGiorgio** [comment]
Very nice. Thank you.
